services:
  browser-rc:
    build:
      context: .
      dockerfile: Dockerfile
    user: '${BROWSER_RC_UID:-1000}:${BROWSER_RC_GID:-1000}'
    container_name: browser-rc
    environment:
      HTTP_PORT: '${HTTP_PORT:-3001}'
    expose:
      - '${HTTP_PORT:-3001}'
    networks:
      - browser-rc-access
    ports:
      - '${HTTP_PORT:-3001}:${HTTP_PORT:-3001}'
    restart: unless-stopped
    shm_size: 1gb
    stdin_open: true
    tty: true
    volumes:
      - ${HOME}/.config/google-chrome:/home/node/.config/google-chrome
      - ./data/docker/runs:/data/runs

  browser-rc-docs:
    container_name: browser-rc-docs
    environment:
      DEFAULT_MODEL_RENDERING: model
      SWAGGER_JSON: /openapi.yaml
    image: swaggerapi/swagger-ui
    networks:
      - browser-rc-access
    ports:
      - '8081:8080'
    restart: unless-stopped
    volumes:
      - ./openapi/openapi.yaml:/openapi.yaml:ro

networks:
  browser-rc-access:
    driver: bridge
    name: browser-rc-access
